site:
  title: catcodeme's blog
  url: https://catcodeme.github.io
  start_page: blog::start.adoc
content:
  sources:
  - url: https://github.com/CatCodeMe/catcodeme.github.io.git
    branches: main
    start_path: docs
ui:
  bundle:
    url: ./ui/default_ui.zip
  supplemental_files: ./supplemental-ui
runtime:
  fetch: true
  log:
    failure_level: error
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
  extensions:
    - '@asciidoctor/tabs'
antora:
  extensions:
    - require: '@antora/lunr-extension'
      snippet_length: 50
      languages: [en,zh]
    - require: '@sntke/antora-mermaid-extension'
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
      script_stem: header-scripts
      mermaid_initialize_options:
        startOnLoad: true